name: Keep Render Apps Awake (IST schedule, daily)

on:
  schedule:
    # Runs every 5 min from 08:55 to 09:30 IST daily
    - cron: "25,30,35,40,45,50,55,0 3 * * *" # 03:25 → 04:00 UTC
  workflow_dispatch: # allows manual run

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoints
        run: |
          echo "Pinging endpoints to wake Render apps..."

          # List of endpoints (no commas)
          endpoints=(
            "https://think-twice-server.onrender.com/health"
            "https://townsquare-kg8z.onrender.com/health"
            "https://devsphere-us67.onrender.com/"
          )

          for url in "${endpoints[@]}"; do
            echo "Pinging $url"
            res=$(curl -s -o /dev/null -w "%{http_code} %{time_total}" --max-time 25 "$url") || res="000 0"
            echo "$(date -u +"%Y-%m-%d %H:%M:%S UTC") - $url => $res"
          done
