name: Keep Render Apps Awake (IST schedule, daily)

on:
  schedule:
    # Runs at 08:50 and 08:55 IST daily
    - cron: "20 2 * * *"   # 08:50 IST → 02:20 UTC
    - cron: "25 2 * * *"   # 08:55 IST → 02:25 UTC
  workflow_dispatch: # allows manual run

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoints
        run: |
          echo "Pinging endpoints to wake Render apps..."

          # List of endpoints (no commas)
          endpoints=(
            "https://townsquare-wenh.onrender.com/health"
            "https://townsquare-kg8z.onrender.com/health"
            "https://devsphere-us67.onrender.com/"
          )

          for url in "${endpoints[@]}"; do
            echo "Pinging $url"
            # curl: silent, capture HTTP status and time, max-time 25s
            res=$(curl -s -o /dev/null -w "%{http_code} %{time_total}" --max-time 25 "$url") || res="000 0"
            echo "$(date -u +"%Y-%m-%d %H:%M:%S UTC") - $url => $res"
          done
